name: 'tests Mac'

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set Environment
      run: echo "TMPDIR=${TMPDIR}" >> $GITHUB_ENV

    - name: Restore ShaderC from Cache
      id: restore_shaderc_cache
      uses: actions/cache@v2
      with:
        path: shaderc
        key: ${{ runner.os }}-shaderc

    - name: Build ShaderC
      if: steps.restore_shaderc_cache.outputs.cache-hit != 'true'
      run: |
        git clone https://github.com/google/shaderc && \
        cd shaderc && \
        ./utils/git-sync-deps && \
        cmake -H. -Bcmake-build-release -DCMAKE_BUILD_TYPE=Release && \
        cmake --build cmake-build-release -j8

    - name: Install dependencies
      run: |
        (cd shaderc && sudo cmake --install cmake-build-release)
        brew install python3 curl pkg-config sdl2 ffmpeg ninja glm spirv-cross
        # https://docs.brew.sh/Homebrew-and-Python
        pip3 install --upgrade pip
        # Install meson
        pip3 install meson

    - name: Build
      run: |
        export MESON_BACKEND=ninja
        export PKG_CONFIG_PATH=$PWD/venv/lib/pkgconfig
        make

